version: '3'
services:
  frontend:
    build: ./front
    restart: always
    ports:
      - '3000:3000'
    links:
      - backend
  backend:
    build: ./back
    restart: always
    ports:
      - '4001:4001'
